version: 1.0.{build}
image: Visual Studio 2017
environment:
  _PlatformToolset: v141
  _TargetPlatform: 8.1
  _SkipTest: true
platform:
  - x64
configuration:
  - Debug
  - Release
artifacts:
  - path: '**\*.exe'
build:
  project: build.xml
  verbosity: normal
test:
  assemblies:
    only:
      - '**\*.dll'
