version: 1.0.{build}
image: Visual Studio 2017
environment:
  _PlatformToolset: v141
  _TargetPlatform: 8.1
  _SkipTest: true
platform:
  - x64
configuration:
  - Debug
  - Release
artifacts:
  - path: '**\*.zip'
build:
  project: build.xml
  verbosity: normal
test_script:
  - cmd: vstest.console /logger:Appveyor /Platform:%platform% /InIsolation build/test/%configuration%/%platform%/test.dll
