version: 1.0.{build}
image: Visual Studio 2017
environment:
  PlatformToolset: v141
  TargetPlatformVersion: 8.1
  BuildVersion: $(version)_$(APPVEYOR_BUILD_VERSION)
platform:
  - x64
configuration:
  - Debug
  - Release
artifacts:
  - path: '**\*.zip'
build:
  project: build.xml
  verbosity: normal
test_script:
  - cmd: msbuild build.xml /t:RunTest
